### PR TITLE
Allow commented out lines with -f option

### PR DESCRIPTION
**Pull request by matlink**

### CODE REVIEW

**Comment by Mickael-Martin** [comment]
No merge since 2015 ?

**Comment by zerodeux** [comment]
Uh oh, I think I missed the notification back in 2015, otherwise I would have merged it immediatly. It's a safe and useful patch.

**Comment by Mickael-Martin** [comment]
Can you merge, please ? We have this message : 
"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
pussh"

**Comment by zerodeux** [comment]
Merged, and pussh 1.1 released, thanks !

**Pull request merged**
